### ISSUE TITLE
pytorch 1.8 support?

### ISSUE THREAD

**Issue by ggilley** [sugarme/gotch#25]
I see you started on pytorch 1.7 support, but didn't complete it. What's involved in getting to pytorch 1.8?

My current use case is simpler than your ambition. I just have a model (and more once I solve this) I want to use golang to serve. I need to load the jit module and get arguments to it and values back. I think golang is a better api serving solution than cpp :-)

**Comment by sugarme** [comment]
@ggilley ,

FYI, gotch for Pytorch 1.8 C++ APIs will be updated soon. Gotch versioning and Pytorch version are loosely coupled and we are still improving gotch APIs and make them stable. 
What is your use case that needs Pytorch v1.8?

**Comment by ggilley** [comment]
Two things. One was Nvidia 3090 GPU support. The other was some TorchScript python constructs in 1.8 (dict comprehension and one other which slips my mind at the moment).

**Comment by sugarme** [comment]
@ggilley ,

You can try libtorch 1.7 with CUDA 11.0 from this [download link](https://download.pytorch.org/libtorch/cu110/libtorch-cxx11-abi-shared-with-deps-1.7.0%2Bcu110.zip). I used this in docker image and it runs okay.

Please be specific about "dict comprehension"? which types missing in your use case? Have a look at [this example](https://github.com/sugarme/gotch/tree/master/example/jit-train) and [this](https://github.com/sugarme/gotch/tree/master/example/jit) and try to load your jit module to see how you go with it. If an error occurs, please report so that we can deal with it. Python and Go are different languages, we also have C++ behind the scene as well.  So please try and report so we can improve.

**Comment by ggilley** [comment]
"dict comprehension" refers to the python language construct.

`self.d_id_to_word: Dict[int, str] = {v: k for k, v in self.word_to_id.items()}`

It was not part of the 1.7 TorchScript jit. It was added in 1.8. It doesn't affect the interfaces, just the guts.

**Comment by mauriciocm9** [comment]
any update on this issue? we're trying to deploy a model with jit that uses torchvision::op::nms package, i tried installing torchvision c++ library but it doesn't seem to have this method. This is the model we're trying to deploy https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html#deployment-with-tracing-or-scripting by the way great work with this package, any suggestion to help are welcome

**Comment by sugarme** [comment]
Hi @mauriciocm9,

We intend to upgrade libtorch 1.8 and try to find my time this month. I had a quick look at `torchvision::op::nms` and even if `gotch` upgrade libtorch 1.8, it will not include `torchvision` APIs. Gotch implements its own subpackage `gotch/vision`. However, if your model requires Pytorch JIT 1.8, you can go ahead and install Libtorch 1.8 for your system to try out. I would love to know and improve loading JIT model in gotch.
