### ISSUE TITLE
ImageNet.LoadImageAndResize224 does not work with linux symbolic link

### ISSUE THREAD

**Issue by Claus1** [sugarme/gotch#27]
For avoiding copying datasets between projects I intensively use symbolic links.  LoadImageAndResize224 does not count it.
ImageNet - LoadImageAndResize224/LoadImageAndResize method call: ImageNet - LoadImageAndResize method call: Libtorch API Error: can't fopen

**Comment by sugarme** [comment]
@Claus1 ,

My appology, I thought I missed this issue and revisit it. However, I find the issue seem to be your individual project rather than gotch. I am going to close #27. Thanks for raising it and feel free to continue discussion on [github discussion](https://github.com/sugarme/gotch/discussions) if you wish.
