### ISSUE TITLE
How to drop gpu cache when drop the tensor?

### ISSUE THREAD

**Issue by ZonghaoWang** [sugarme/gotch#47]
Hi.
    When I create a tensor on GPU, and Drop it, but the memory not free when I use nvidia-smi until the process end?

**Comment by sugarme** [comment]
@ZonghaoWang ,

Pytorch provides somes Python APIs such as `torch.cuda.empty_cache` but not available in C++ APIs. There's [a way to do it in C++ as mention here](https://discuss.pytorch.org/t/how-to-free-gpu-memory-of-at-tensor-in-aten-c/18408).  It would be nice to have one in gotch, not priority though. 

In addition, [Pytorch documentation](https://pytorch.org/docs/master/notes/cuda.html#memory-management) mentions that even if you delete GPU memory cache, you won't increase memory available for Pytorch. 

Feel free to contribute if you come up with any idea otherwise I am closing #47 and might revisite when C++ API available. Thanks.
